# Aegis V2 Scan Profiles - Optimized for Massive Scale

profiles:
  # For scanning 10,000+ hosts
  massive:
    max_concurrency: 10000
    worker_pool_size: 2000
    rate_limit: 20000
    burst_limit: 30000
    chunk_size: 2000
    batch_size: 500
    adaptive_throttling: true
    stream_results: true
    use_connection_pool: true
    description: "Ultra-high performance mode for 10k+ hosts"
    
  # For scanning 5,000 hosts  
  ultra:
    max_concurrency: 5000
    worker_pool_size: 1000
    rate_limit: 10000
    burst_limit: 15000
    chunk_size: 1000
    batch_size: 250
    adaptive_throttling: true
    stream_results: true
    use_connection_pool: true
    description: "High performance mode for 5k hosts"
    
  # For scanning 1,000 hosts
  turbo:
    max_concurrency: 2000
    worker_pool_size: 500
    rate_limit: 5000
    burst_limit: 7500
    chunk_size: 500
    batch_size: 100
    adaptive_throttling: true
    stream_results: false
    use_connection_pool: true
    description: "Turbo mode for 1k hosts"
    
  # Balanced performance
  balanced:
    max_concurrency: 1000
    worker_pool_size: 200
    rate_limit: 2000
    burst_limit: 3000
    chunk_size: 250
    batch_size: 50
    adaptive_throttling: true
    stream_results: false
    use_connection_pool: true
    description: "Balanced mode for general use"

# Performance tuning recommendations
tuning:
  # System limits (ulimit recommendations)
  recommended_file_descriptors: 65535
  recommended_max_processes: 65535
  
  # Network tuning
  tcp_tw_reuse: true
  tcp_fin_timeout: 15
  tcp_keepalive_time: 600
  
  # Memory considerations
  # massive mode: ~4-8GB RAM
  # ultra mode: ~2-4GB RAM
  # turbo mode: ~1-2GB RAM
  # balanced mode: ~512MB-1GB RAM
